### PR TITLE
NSO Update

### PR DESCRIPTION
**Pull request by gerad-not-edgar**

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
Why some are smaller than original, we tend to follow 512px wide size

**Comment by gerad-not-edgar** [comment]
Truth be told, these are just the sizes I have. No sense in making the image larger to fit the standard; will display the same if it doesn't get degraded upon resizing. As someone who has done some horrific things to some of these images previously uploaded to get the "best possible image", I'm trying to just leave these as Nintendo apparently intended. It's a trade of a little bit of quality/resolution for color accuracy for some. I think the difference is pretty negligible for what Retroarch displays. In many instances, NSO has the best images of a lot of these games; in my brain it makes sense to standardize to these images, vs these heavily edited collections people have created. I'd rather see something closer to the original that doesn't have artificial sharpness and dramatically oversaturated colors. The below pic is 4k. It confirmed to me that it isn't just resizing 512x512, but I don't think the difference is so dramatic that a slightly crisper image is preferable to one that isn't oversaturated. 
BUT... I can do whatever you want.
Untitled

**Comment by RobLoach** [comment]
I'm indifferent on this one. They all look the same-ish to me :shrug: 

The size being divisible by 512 is more important for RGUI/lower powered devices where it won't use antialiasing on image scaling. But again, I'm completely indifferent on this, they all look relatively the same-ish to me.

Side-note. What's "NSO"? Curious.

**Comment by gerad-not-edgar** [comment]
NSO = Nintendo Switch Online. It amazes me how inconsistent they are when you look at like Earthbound and Killer Instinct vs the bulk of them achieve closer to a true black. You'd think the source would have kept all these assets, or at least spent more time on cleaning them up. Do you want them blown up to 512 width where applicable?

**Comment by gerad-not-edgar** [comment]
@RobLoach @MarcoEstevez What do you want done with these in order to merge them? Thanks

**Comment by MarcoEstevez** [comment]
Looks good to me!

**Pull request merged**
