### PR TITLE
add some missing snaps and titles

### PR DESCRIPTION
**Pull request by arianrhodsandlot**
I created [a program](https://github.com/arianrhodsandlot/libretro-thumbnails-tinker) that helps me obtain missing thumbnails more efficiently, although manual actions are still required...

If this type of PR is acceptable, I would like to add more missing thumbnails like this when I have free  time!

### CODE REVIEW

**Comment by arianrhodsandlot** [comment]
@RobLoach Could you please help me with reviewing this pull request? Thank you.

**Comment by RobLoach** [comment]
These are great! And I really like your tinker application. Will definitely make finding the missing ones easier....

As for the images, looks like they have a one-pixel white bar at the bottom? Is there a way to remove the white at the bottom? I believe it could be possible to automate removing the white pixel at the bottom through the command line, but I haven't done that in a while.

**Comment by arianrhodsandlot** [comment]
Oh I didn't notice these white pixels since my image viewer has a white background 🥲 ... I'll solve this soon and update them.

**Comment by arianrhodsandlot** [comment]
Now updated by imagemagick👌

**Comment by RobLoach** [comment]
That's magic! :magic_wand::magic_wand::magic_wand::magic_wand:

**Pull request merged**
