### PR TITLE
Change homebrew title Micro Mages to use images from official presskit, add a boxart image.

### PR DESCRIPTION
**Pull request by chexo3**
The official presskit at [Morphcat Games' website](http://morphcat.de/micromages/presskit/) contains a box art image suitable for use as a box art thumbnail. I noticed there was no boxart when I was in RetroArch, and I remembered about the press kit, so I've created a pull request to add the box art image from that press kit, and change the screenshot image and title screen image to use images from that press kit. The zip files at that page provide an image that is identical, and an image that is very visually similar, respectively, for the title screen and gameplay screenshots. 

At this time I am not sure what license exactly these images fall under. I imagine they are okay to redistribute, being part of a press kit, but if more information is needed I can contact the developers via their Discord server.

### CODE REVIEW

**Comment by chexo3** [comment]
Update: Devs clarified this use is okay, they put these files together for use by journalists, or for uses like this.

**Review by RobLoach — CHANGES_REQUESTED** [review]
Looks great, but would you mind updating the width to 512px? Thanks!

**Comment by chexo3** [comment]
The width of which image exactly? The boxart makes sense, I'll do that one, but the named snaps and named titles in this repo are in the native resolution, 256x240. I scaled the images back to 256 wide, but they had overscan cut off before being put into the presskit, making them 256x224.

Is the scaling of the gameplay screens a new change?

**Comment by chexo3** [comment]
`Named_Titles` image and `Named_Snaps` image both resized to 512px in width, aspect ratio preserved.

**Comment by RobLoach** [comment]
As long as they're <=512px wide, then that's perfect. Thanks!

**Comment by chexo3** [comment]
Well then, they are now. All three images are wider than 512px. Specifically, the two images created from gameplay, the title screen snap and the in-game snap, were scaled back to their original resolution from being 3x bigger in the presskit, and then after receiving feedback scaled to 2x the original resolution. Compression settings should not have resulted in any loss of quality from these multiple steps. They should be perfect.

And soon, I'll be able to see the boxart for one of my favorite games in RetroArch!

**Comment by kwyxz** [comment]
@chexo3 the maximum width ought to be 512pix, so if the boxart is bigger please scale it down, thanks

**Comment by chexo3** [comment]
It’s only slightly wider than 512. Is there a code/technical reason it can’t be that wide? Resizing to 512px wide might look weird, I will look at it on the computer in a bit, but it’s already pretty small, I would rather let clients resize it themselves when displaying it, because then we’re not limiting the resolution to smaller than is publicly available, and unlike with the gameplay snaps this would probably be a change that can’t be easily reversed losslessly.

**Comment by RobLoach** [comment]
Resized and merged. Thanks a lot!

> Is there a code/technical reason it can’t be that wide?

Yes. We've standardized on 512px wide because on small display sizes we're able to scale it nicely into different sizes quickly.

**Comment by chexo3** [comment]
Ah. Do you still need me to do something with this or is this done?

**Comment by RobLoach** [comment]
Nope! It be done :wink: Thanks so much!!! I love this game. Streamed it multiplayer last year on Twitch! https://www.twitch.tv/videos/433792675

**Comment by chexo3** [comment]
Good! I love it too, and remembered the press kit, hence the PR. Perfect for this!

**Comment by kwyxz** [comment]
Hmm, something is odd here. The thumbnail was pushed as `Micro Mages (USA) (Unl)` which in theory is fine and coherent with the usual No-Intro naming, but the game name in the DB is simply `Micro Mages` :
```game (
        name "Micro Mages"
        description "Micro Mages is a new platform game for the NES, play solo or with up to 4 players simultaneously. Fight to get the best score or cooperate to overcome challenging levels."
        year "2018"
        developer "Morphcat Games"
        homepage "http://morphcat.de/micromages/"
        rom ( name "Micro Mages.nes" size 40976 crc b0b6b5e4 md5 1062df5838a11e0e17ed590bdc1095c6 sha1 1411f9009cfa944c23b318620da72e395070c650 )```
Correct me if I am wrong but as such RetroArch won't find the thumbnail, will it?

**Comment by RobLoach** [comment]
Good catch, It should be `Micro Mages`.

**Comment by kwyxz** [comment]
Sounds good, I will rename it with my next push. Thanks for the confirmation!

**Comment by kwyxz** [comment]
Fixed in 7bee0d63a2d72c93310adfeaa2d41f19467bbd2e

**Pull request merged**
